= LEHD Schema Changelog ({schemaversion})
Contact Us <ces.qwi.feedback@census.gov>
:ext-relative: {outfilesuffix}
:icons: font
:linkcss:
:copycss:
:toc:
:numbered:
:toclevels: 4
:sectnumlevels: 4

[NOTE]
.Important
==============================================
Feedback is welcome.
Please write us at link:mailto:ces.qwi.feedback@census.gov?subject=LEHD_Schema[ces.qwi.feedback@census.gov].
==============================================

== V4.8.2

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.1

- None ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.1

- None ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.1

- Added IPEDS status flag for partially missing counts
- Updated PSEO earnings to 2019 dollars

== V4.8.1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.0

- None ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.0

- None ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.8.0

- Update of institution list (label_institution.csv)

== V4.8.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.7.0

- Underlying geovintage updated to reflect 2020 TIGER/Line geography (except for CBSAs - "gb" and "gm" features)
- Updated shapefiles based on TIGER/Line 2020 (except for CBSAs - "gb" and "gm" shapefile types) ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.7.0

- None

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.7.0

- Update EmpSpv due to the restructuring of the QWI weights
- Added PSEO metadata files for data partners and coverage
- Underlying geovintage updated to reflect 2020 TIGER/Line geography - except for CBSAs.
Tabulations for "B" and "M" geo_levels continue to use 2019 TIGER/Line geographies.

== V4.7.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.6.0

- None ==

[[changes]] Changes For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.6.0

- Adding PSEO data product

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== Changes from 4.6.0

- Merge PSEO schema files into official release version
- Minor formatting changes

=== Changes from 4.5.0-draft

- Additional status flags on PSEO Earnings
- Additional measures on PSEO Flows to report unobserved/marginally employed
- Earnings reported at 2-digit CIPCODE level
- Institution code changed to 8-digits
- Updated to 2020 CIPCODE

== V4.6.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2020-01-21: Initial release

=== Version 4.6.0 from 4.4.0

- Underlying geovintage updated to reflect 2019 census geography
- Updated shapefiles based on TIGER 2019
- Added documentation of new J2J Earnings indicators (coming soon in next release of J2J data)

== V4.5.0-draft

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2019-05-16: Initial release

=== Version 4.5.0 from 4.4.0

- Added PSEO draft schema csv files
- Added PSEO sourcing and documentation

== V4.4.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2019-02-21: Initial release
- 2019-03-31: Minor layout changes for better readability

=== Version 4.4.0 from 4.3.1

- Underlying geovintage updated to reflect 2018 census geography
- Updated shapefiles based on TIGER 2018
- PR geography labels added
- Added state part to non-metro/non-micro areas in state label files
- Removed nonexistent VT geography from labels

== V4.3.1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2018-10-30: Initial release
- 2019-02-28: Switch to different rendering engine, only stylistic changes

=== Version 4.3.1 from 4.3.0

- 2018-10-30: Due to a change of the geographic boundaries for a WIB in Iowa, the shape files need to be updated.
- Adjust the "supersedes" definition to correctly reference the prior version.

=== Version 4.3.0 from 4.2.0

- Changed the format of the version.txt file.
This does not affect data files, but it does affect the metadata, and thus requires an increase in the minor version.
- Changed the description of the download locations of the QWI files, as part of the "naming" schema.

== V4.3.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2018-06-25: Initial release

=== Version 4.3.0 from 4.2.0

- Changed the format of the version.txt file.
This does not affect data files, but it does affect the metadata, and thus requires an increase in the minor version.
- Changed the description of the download locations of the QWI files, as part of the "naming" schema.

== V4.2-rc1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-12-15: Initial release

=== Version 4.2.0 from 4.1.3

- Updated industry classification from NAICS 2012 to NAICS 2017
- Added J2J Explorer-specific description of metadata for convenience (link:lehd_j2jexplorer_schema.html[lehd_j2jexplorer_schema.html])
- Added a column +ind_level+ to label_industry.csv similar to the +geo_level+
- Added additional columns to the variable metadata schema for greater clarity
* Description,
* Concept,
* Base
- Added a (draft) taxonomy of concepts used in the LEHD data world (link:label_concept_draft.csv[label_concept_draft.csv])
- Fixed the labeling of ownership code +A00+ to correctly reflect scope
- Added files describing the number of quarters of data availability required relative to start and end quarters (link:lags_qwi.csv[] and link:lags_j2j.csv[]), and its metadata (link:variables_lags.csv[])

== V4.2b-draft

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-08-21: Initial release
- 2017-09-01: Incorporates forgotten updates to j2japp descriptions.
This does not affect the structure or contents of any released data files, but it affects the unreleased J2J app updates downstream.
- 2017-09-07: clarifying the version.txt description - removed the mention of fips replacing by geonum
- 2017-09-07: Moved stusps to the geography section, where it rightfully belongs.
- 2017-09-07: Clarified language and usage of metropolitan area codes in label_geography_metro.csv, removed unused label_geography_cbsa.csv
- 2017-09-07: Expanded definition of [geohi] to include CBSA codes for metropolitan areas
- 2017-10-30: Description on J2JOD earnings measures reversed, fixed.
Only affects the J2J app metadata.
- 2017-12-18: Description on J2JOD earnings measures reversed, should have also fixed on J2JOD description.

=== Version 4.2b-draft from V4.2a-draft

- See https://github.com/labordynamicsinstitute/qwi_schemas/milestone/12?closed=1[Github]

=== Version 4.2a-draft from 4.1.1

- See https://github.com/labordynamicsinstitute/qwi_schemas/milestone/5?closed=1[Github]

== V4.2a-draft

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-04-04: Initial release

=== Version 4.2a-draft from 4.1.1

- See github

== V4.2.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-12-15: Initial release
- 2018-03-23: Fix EOL issues
- 2018-06-04: Additional EOL issues

=== Version 4.2.0 from 4.1.3

- Updated industry classification from NAICS 2012 to NAICS 2017
- Added a column +ind_level+ to label_industry.csv similar to the +geo_level+
- Added additional columns to the variable metadata schema for greater clarity
* Description,
* Concept,
* Base
- Added a (draft) taxonomy of concepts used in the LEHD data world (link:label_concept_draft.csv[label_concept_draft.csv])
- Fixed the labeling of ownership code +A00+ to correctly reflect scope
- Added files describing the number of quarters of data availability required relative to start and end quarters (link:lags_qwi.csv[] and link:lags_j2j.csv[]), and its metadata (link:variables_lags.csv[])

== V4.1-rc3

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2016-08-08: Initial release

=== Version 4.1-rc1 from 4.0.5

- 2016-08-08: Implemented select changes from V4.1d-draft: Key changes are
- Changed structure of state-level geography labels (flat directory structure) e5dbe97
- Describes National QWI files and J2J files (both of which are still in beta), added J2J, National QWI spec
- added additional geo_level for CBSA (complete), additional description, sources in label_geo_level.csv 1eb399f,27a2674
- 2016-08-31: adjusted AL, AR, GA, IA, KY, LA, MN, MS, NM, PA, TN, TX metropolitan areas for 2016 geo vintage

==== In more detail

- added geohi category of ALL, US, add naming_geohi.csv 89617e3
- added naming convention for additional filesb
- added agg_level variable 89617e3, 2149623
- Changes to name of variable schema files (qwipu -> qwi), addition of variability and rate variable schema files. 89617e3
- Addition of a column identifying the type of variable on QWI 89617e3
- Renamed file from QWIPU_Data_Schema.pdf to lehd_public_use_schema.pdf 89617e3
- Addition of variable schema description for J2J 1a57250
- Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files) d9f8387 f7cc524
- Updated documentation-generating scripts to the latest.
Documents are now identified by date, not revision 8136f0c
- Added a concatenation of geography files as label_geography.csv. 8136f0c, 39ecfc9
- Added a column geo_level to all label_geography_* files a32bb4c
- Changed fipsnum to force readin of FIPS as character, include geo_level, US. a32bb4c
- Added additional legal values for firmage and firmsize, as used by J2J a32bb4c
- Added Federal government to files (for National QWI) 942dd0a, 1654288
- Clarified description of filenaming components 8888529, 8d580f6
- Sundry small additional changes, building out the schema 28d7c6f
- Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released. 3a0975e

=== Version 4.1-rc2 from 4.1-rc1

- 2016-08-10: Added description,definition of SHP files
- 2016-08-11: Modified Indicator Names for J2J variable metadata.

=== Version 4.1-rc3 from 4.1-rc2

- 2016-08-31: adjusted AL, AR, GA, IA, KY, LA, MN, MS, NM, PA, TN, TX metropolitan areas for 2016 geo vintage

For additional details, please consult the previous draft versions:

- link:../V4.1-draft[../V4.1-draft]
- link:../V4.1b-draft[../V4.1b-draft]
- link:../V4.1c-draft[../V4.1c-draft]
- link:../V4.1d-draft[../V4.1d-draft]

== V4.1-rc2

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2016-08-08: Initial release

=== Version 4.1-rc1 from 4.0.5

- 2016-08-08: Implemented select changes from V4.1d-draft: Key changes are
- Changed structure of state-level geography labels (flat directory structure) e5dbe97
- Describes National QWI files and J2J files (both of which are still in beta), added J2J, National QWI spec
- added additional geo_level for CBSA (complete), additional description, sources in label_geo_level.csv 1eb399f,27a2674

==== In more detail

- added geohi category of ALL, US, add naming_geohi.csv 89617e3
- added naming convention for additional filesb
- added agg_level variable 89617e3, 2149623
- Changes to name of variable schema files (qwipu -> qwi), addition of variability and rate variable schema files. 89617e3
- Addition of a column identifying the type of variable on QWI 89617e3
- Renamed file from QWIPU_Data_Schema.pdf to lehd_public_use_schema.pdf 89617e3
- Addition of variable schema description for J2J 1a57250
- Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files) d9f8387 f7cc524
- Updated documentation-generating scripts to the latest.
Documents are now identified by date, not revision 8136f0c
- Added a concatenation of geography files as label_geography.csv. 8136f0c, 39ecfc9
- Added a column geo_level to all label_geography_* files a32bb4c
- Changed fipsnum to force readin of FIPS as character, include geo_level, US. a32bb4c
- Added additional legal values for firmage and firmsize, as used by J2J a32bb4c
- Added Federal government to files (for National QWI) 942dd0a, 1654288
- Clarified description of filenaming components 8888529, 8d580f6
- Sundry small additional changes, building out the schema 28d7c6f
- Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released. 3a0975e

=== Version 4.1-rc2 from 4.1-rc1

- 2016-08-10: Added description,definition of SHP files
- 2016-08-11: Modified Indicator Names for J2J variable metadata.

For additional details, please consult the previous draft versions:

- link:../V4.1-draft[../V4.1-draft]
- link:../V4.1b-draft[../V4.1b-draft]
- link:../V4.1c-draft[../V4.1c-draft]
- link:../V4.1d-draft[../V4.1d-draft]

== V4.1-rc1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2016-08-08: Initial release

=== Version 4.1-rc1 from 4.0.5

- 2016-08-08: Implemented select changes from V4.1d-draft: Key changes are
- Changed structure of state-level geography labels (flat directory structure) e5dbe97
- Describes National QWI files and J2J files (both of which are still in beta), added J2J, National QWI spec
- added additional geo_level for CBSA (complete), additional description, sources in label_geo_level.csv 1eb399f,27a2674

==== In more detail

- added geohi category of ALL, US, add naming_geohi.csv 89617e3
- added naming convention for additional files
- added agg_level variable 89617e3, 2149623
- Changes to name of variable schema files (qwipu -> qwi), addition of variability and rate variable schema files. 89617e3
- Addition of a column identifying the type of variable on QWI 89617e3
- Renamed file from QWIPU_Data_Schema.pdf to lehd_public_use_schema.pdf 89617e3
- Addition of variable schema description for J2J 1a57250
- Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files) d9f8387 f7cc524
- Updated documentation-generating scripts to the latest.
Documents are now identified by date, not revision 8136f0c
- Added a concatenation of geography files as label_geography.csv. 8136f0c, 39ecfc9
- Added a column geo_level to all label_geography_* files a32bb4c
- Changed fipsnum to force readin of FIPS as character, include geo_level, US. a32bb4c
- Added additional legal values for firmage and firmsize, as used by J2J a32bb4c
- Added Federal government to files (for National QWI) 942dd0a, 1654288
- Clarified description of filenaming components 8888529, 8d580f6
- Sundry small additional changes, building out the schema 28d7c6f
- Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released. 3a0975e

For additional details, please consult the previous draft versions:

- link:../V4.1-draft[../V4.1-draft]
- link:../V4.1b-draft[../V4.1b-draft]
- link:../V4.1c-draft[../V4.1c-draft]
- link:../V4.1d-draft[../V4.1d-draft]

== V4.1-draft

== [[changes]] Changes

=== This version from previous releases of this document

- 2015-02-25: corrected flag values
- 2015-02-25: documents are now identified by date, not revision
- 2015-03-10: Correction of the TIGER vintage that is used for geographic references

=== Version 4.1-draft from 4.0

- added J2J, National QWI spec

== V4.1d-draft

== [[changes]] Changes

=== This version from previous releases of V4.1 draft schema documents

- 2015-02-25: corrected flag values
- 2015-02-25: documents are now identified by date, not revision
- 2015-03-10: Correction of the TIGER vintage that is used for geographic references
- 2015-03-11: Added URL for J2J
- 2015-03-11: Correction of typo in type naming convention, rename of naming_fipsalpha.csv to naming_geohi.csv to be consistent.
- 2015-03-17: Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released.
- 2015-04-24: Changes to alternate name of SepSnx and EmpSpv, tentative rate names
- 2015-04-26: Changes to name of variable schema files (qwipu -> qwi), addition of variability variable schema files.
- 2015-04-28: Fixed small typos in QWI variable short names
- 2015-05-18: Updated agg_level description, replaced agg_level.csv file
- 2015-05-22: Fixed minor rendering bug for QWI rate variability names.
No change to actual metadata.
- 2015-06-09: Fixed a minor coding error in label_fipsnum.csv, added a concatenation of geography files as label_geography_all.csv.
- 2015-08-07: Minor text change for agg_level, modified agg_level file.
- 2015-08-12: Removed the last 4 rows of variables_j2jod.csv, since they are not on the current beta J2JOD files.
- 2015-08-25: Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files)
- 2016-03-16: Removed extraneous empty lines
- 2016-04-12: Fixed typo in variables_qwi.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-12: Incorporated all state-level geography from 4.0.5
- 2016-04-12: Added additional geo_level for CBSA (complete)
- 2016-04-12: Added additional agg_level values
- 2016-04-12: Clarified labels of j2jod identifiers
- 2016-04-12: Renamed label_geography_all as label_geography
- 2016-04-12: Added a column geo_level to all label_geography_* files
- 2016-08-08: Corrected erroneous Oregon geography labels.

=== Version 4.1d-draft from 4.0.1

- added J2J, National QWI spec
- added geohi category of ALL, US
- added definitions of variability measures
- added definitions of rates on separate file
- added naming convention for additional files
- added agg_level variable
- added additional geo_level for CBSA (complete)
- added SHP files and description thereof

== V4.1c-draft

== [[changes]] Changes

=== This version from previous releases of this document

- 2015-02-25: corrected flag values
- 2015-02-25: documents are now identified by date, not revision
- 2015-03-10: Correction of the TIGER vintage that is used for geographic references
- 2015-03-11: Added URL for J2J
- 2015-03-11: Correction of typo in type naming convention, rename of naming_fipsalpha.csv to naming_geohi.csv to be consistent.
- 2015-03-17: Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released.
- 2015-04-24: Changes to alternate name of SepSnx and EmpSpv, tentative rate names
- 2015-04-26: Changes to name of variable schema files (qwipu -> qwi), addition of variability variable schema files.
- 2015-04-28: Fixed small typos in QWI variable short names
- 2015-05-18: Updated agg_level description, replaced agg_level.csv file
- 2015-05-22: Fixed minor rendering bug for QWI rate variability names.
No change to actual metadata.
- 2015-06-09: Fixed a minor coding error in label_fipsnum.csv, added a concatenation of geography files as label_geography_all.csv.
- 2015-08-07: Minor text change for agg_level, modified agg_level file.
- 2015-08-12: Removed the last 4 rows of variables_j2jod.csv, since they are not on the current beta J2JOD files.
- 2015-08-25: Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files)
- 2016-03-16: Removed extraneous empty lines
- 2016-04-12: Fixed typo in variables_qwi.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-13: Fixed typo in variables_qwi.csv (HirAS, HirNS, and status variables)
- 2016-04-13: Fixed typo in variables_qwi*v.csv (HirAS, HirNS)

=== Version 4.1c-draft from 4.0

- added J2J, National QWI spec
- added geohi category of ALL, US
- added definitions of variability measures
- added definitions of rates on separate file
- added naming convention for additional files
- added agg_level variable

== V4.1b-draft

== [[changes]] Changes

=== This version from previous releases of this document

- 2015-02-25: corrected flag values
- 2015-02-25: documents are now identified by date, not revision
- 2015-03-10: Correction of the TIGER vintage that is used for geographic references
- 2015-03-11: Added URL for J2J
- 2015-03-11: Correction of typo in type naming convention, rename of naming_fipsalpha.csv to naming_geohi.csv to be consistent.
- 2015-03-17: Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released.
- 2015-04-24: Changes to alternate name of SepSnx and EmpSpv, tentative rate names
- 2015-04-26: Changes to name of variable schema files (qwipu -> qwi), addition of variability variable schema files.
- 2015-04-28: Fixed small typos in QWI variable short names
- 2015-05-18: Updated agg_level description, replaced agg_level.csv file
- 2015-05-22: Fixed minor rendering bug for QWI rate variability names.
No change to actual metadata.
- 2015-06-09: Fixed a minor coding error in label_fipsnum.csv

=== Version 4.1b-draft from 4.0

- added J2J, National QWI spec
- added geohi category of ALL, US
- added definitions of variability measures
- added definitions of rates on separate file
- added naming convention for additional files
- added agg_level variable
- added a concatenation of geography files as label_geography_all.csv.
- added label_geography_us.csv for completeness

== V4.1.3

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-08-21: Initial release

=== Version 4.1.3 from 4.1.2

- 2017-08-15: Updated LEHD shape files for Texas WIB definitions
- 2017-08-15: Update the source links of metro definitions from http://www.census.gov/population/metro/ (broken) to https://www.census.gov/programs-surveys/metro-micro.html
- 2017-08-21: Corrected naming of three of the status flags that have "Rate" at the end.
That should be just "R".

=== Version 4.1.2 from 4.1.1

- 2017-06-19: Updated LEHD shape files, Louisiana and Alabama WIB definitions

=== Version 4.1.1 from 4.1.0

- 2017-03-06: Modifed naming_geo_cat.csv, gb value to read "Metropolitan (complete)", gm to "Metropolitan/Micropolitan (state parts)"
- 2017-03-06: Updated reference in shapefile description to Job-to-Job Explorer to point to the recently released Beta webap, updated title to refer to the same name as the naming_geo_cat.csv uses
- 2017-03-06: Updated TIGER references to 2016 in shapefile description
- 2017-03-06: Modifed label_geo_level.csv, B value to read "Metropolitan (complete)"
- 2017-03-06: Added referenced in the same file to where to find the CBSA code underlying the state-part definitions
- 2017-03-06: Added a new file label_geography_metro.csv
- 2017-03-06: Changed references where appropriate from label_geography_cbsa to label_geography_metro
- 2017-03-06: Added additional aggregation levels, changed some labels
- 2017-03-06: Removed two variables from variables_j2jod.csv that were not actually on the CSV file
- 2017-03-07: Updated 2016 geography in shapefiles
- 2017-03-07: Corrected naming of files inside shapefile ZIP files

== V4.1.2

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-06-19: Initial release
- 2017-08-21: Corrected naming of three of the status flags that have "Rate" at the end.
That should be just "R".

=== Version 4.1.2 from 4.1.1

- 2017-06-19: Updated LEHD shape files, Louisiana and Alabama WIB definitions

=== Version 4.1.1 from 4.1.0

- 2017-03-06: Modifed naming_geo_cat.csv, gb value to read "Metropolitan (complete)", gm to "Metropolitan/Micropolitan (state parts)"
- 2017-03-06: Updated reference in shapefile description to Job-to-Job Explorer to point to the recently released Beta webap, updated title to refer to the same name as the naming_geo_cat.csv uses
- 2017-03-06: Updated TIGER references to 2016 in shapefile description
- 2017-03-06: Modifed label_geo_level.csv, B value to read "Metropolitan (complete)"
- 2017-03-06: Added referenced in the same file to where to find the CBSA code underlying the state-part definitions
- 2017-03-06: Added a new file label_geography_metro.csv
- 2017-03-06: Changed references where appropriate from label_geography_cbsa to label_geography_metro
- 2017-03-06: Added additional aggregation levels, changed some labels
- 2017-03-06: Removed two variables from variables_j2jod.csv that were not actually on the CSV file
- 2017-03-07: Updated 2016 geography in shapefiles
- 2017-03-07: Corrected naming of files inside shapefile ZIP files

== V4.1.1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2017-03-06: Initial release
- 2017-08-21: Corrected naming of three of the status flags that have "Rate" at the end.
That should be just "R".

=== Version 4.1.1 from 4.1.0

- 2017-03-06: Modifed naming_geo_cat.csv, gb value to read "Metropolitan (complete)", gm to "Metropolitan/Micropolitan (state parts)"
- 2017-03-06: Updated reference in shapefile description to Job-to-Job Explorer to point to the recently released Beta webap, updated title to refer to the same name as the naming_geo_cat.csv uses
- 2017-03-06: Updated TIGER references to 2016 in shapefile description
- 2017-03-06: Modifed label_geo_level.csv, B value to read "Metropolitan (complete)"
- 2017-03-06: Added referenced in the same file to where to find the CBSA code underlying the state-part definitions
- 2017-03-06: Added a new file label_geography_metro.csv
- 2017-03-06: Changed references where appropriate from label_geography_cbsa to label_geography_metro
- 2017-03-06: Added additional aggregation levels, changed some labels
- 2017-03-06: Removed two variables from variables_j2jod.csv that were not actually on the CSV file
- 2017-03-07: Updated 2016 geography in shapefiles
- 2017-03-07: Corrected naming of files inside shapefile ZIP files

== V4.1.0

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2016-09-26: Initial release
- 2016-10-06: Fixed a rendering issue with an empty column.
- 2016-10-06: Modified the label for firm age and firm size to contain mention of "Not Available For Public-Sector Firms"
- 2016-10-06: Changed description of agg_level
- 2017-03-06: Removed two variables from variables_j2jod.csv that were not actually on the CSV file
- 2017-03-06: Corrected bad reference to release RXXXX, which should have been R2016Q4
- 2017-03-07: Corrected naming of files inside shapefile ZIP files
- 2017-08-21: Corrected naming of three of the status flags that have "Rate" at the end.
That should be just "R".

=== Version 4.1 from 4.0.5

- 2016-08-08: Implemented select changes from V4.1d-draft: Key changes are
- Changed structure of state-level geography labels (flat directory structure)
- Describes National QWI files and J2J files (both of which are still in beta), added J2J, National QWI spec
- added additional geo_level for CBSA (complete), additional description, sources in label_geo_level.csv
- 2016-08-10: Added description,definition of SHP files
- 2016-08-11: Modified Indicator Names for J2J variable metadata.
- 2016-08-31: adjusted AL, AR, GA, IA, KY, LA, MN, MS, NM, PA, TN, TX metropolitan areas for 2016 geo vintage

==== In more detail

- added geohi category of ALL, US, add naming_geohi.csv
- added naming convention for additional files
- added agg_level variable
- Changes to name of variable schema files (qwipu -> qwi), addition of variability and rate variable schema files.
- Addition of a column identifying the type of variable on QWI
- Renamed file from QWIPU_Data_Schema.pdf to lehd_public_use_schema.pdf
- Addition of variable schema description for J2J
- Added a extension component [ext] to the file naming convention to reflect availability of Excel files (and PDF files)
- Updated documentation-generating scripts to the latest.
Documents are now identified by date, not revision
- Added a concatenation of geography files as label_geography.csv.
- Added a column geo_level to all label_geography_* files
- Changed fipsnum to force readin of FIPS as character, include geo_level, US.
- Added additional legal values for firmage and firmsize, as used by J2J
- Added Federal government to files (for National QWI)
- Clarified description of filenaming components
- Sundry small additional changes, building out the schema
- Changing of naming convention for to-be-released files based on federal government from fg -> of.
At this time, no such files have been released.

== V4.0.5

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2016-03-15: Initial release
- 2016-04-07: Fixed typo in variables_qwipu.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-13: Fixed typo in variables_qwipu.csv (HirAS, HirNS, and status variables)

=== Version 4.0.1 from 4.0

- 2015-02-24: removed obsolete flag values
- 2015-04-01: updated IL, NE geography definitions

=== Version 4.0.2 from 4.0.1

- 2015-04-01: switched NAICS coding from 2007 to 2012

=== Version 4.0.3 from 4.0.2

- 2015-09-14: switched Geovintage to 2014, updated AK and SD files, added MA.

=== Version 4.0.4 from 4.0.3

- 2015-11-30: updated OR.
- 2015-12-10: Added consolidated geography label file label_geography_all.csv
- 2015-12-22: Updated the identification of the correct geo vintage
- 2015-12-22: Added a link to NAICS 2012 tables
- 2015-12-22: Removing the 99 row in industry values - only used for internal error checking

=== Version 4.0.5 from 4.0.4

- 2016-03-15: updated MO (new WIB code).
- 2016-03-15: Added us/label_geography.csv to have an entry for the National QWI
- 2016-03-15: Added better cross-links between CSV naming schame, and datafile schema
- 2016-03-15: Corrected label_geo_level.csv to include the national level value.
- 2016-03-15: Clarified description of geography codes

== V4.0.4

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2015-12-22: Initial release
- 2016-03-15: Added better cross-links between CSV naming schame, and datafile schema
- 2016-03-15: Corrected label_geo_level.csv to include the national level value.
- 2016-04-07: Fixed typo in variables_qwipu.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-13: Fixed typo in variables_qwipu.csv (HirAS, HirNS, and status variables)

=== Version 4.0.1 from 4.0

- 2015-02-24: removed obsolete flag values
- 2015-04-01: updated IL, NE geography definitions

=== Version 4.0.2 from 4.0.1

- 2015-04-01: switched NAICS coding from 2007 to 2012

=== Version 4.0.3 from 4.0.2

- 2015-09-14: switched Geovintage to 2014, updated AK and SD files, added MA.

=== Version 4.0.4 from 4.0.3

- 2015-11-30: updated OR.
- 2015-12-10: Added consolidated geography label file label_geography_all.csv
- 2015-12-22: Updated the identification of the correct geo vintage
- 2015-12-22: Added a link to NAICS 2012 tables
- 2015-12-22: Removing the 99 row in industry values - only used for internal error checking

== V4.0.3

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2015-09-14: Initial release
- 2015-12-10: Added consolidated geography label file label_geography_all.csv
- 2015-12-22: Updated the identification of the correct geo vintage
- 2016-04-07: Fixed typo in variables_qwipu.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-11: Fixed error in CBSA names (failure to actually update to 2014 Geovintage)
- 2016-04-11: Corrected WIB naming change in Florida and Ohio
- 2016-04-13: Fixed typo in variables_qwipu.csv (HirAS, HirNS, and status variables)

=== Version 4.0.1 from 4.0

- 2015-02-24: removed obsolete flag values
- 2015-04-01: updated IL, NE geography definitions

=== Version 4.0.2 from 4.0.1

- 2015-04-01: switched NAICS coding from 2007 to 2012

=== Version 4.0.3 from 4.0.2

- 2015-09-14: switched Geovintage to 2014, updated AK and SD files, added MA.

== V4.0.2

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2015-04-01: Initial version
- 2015-08-07: Corrected release that the switch to NAICS 2012 was made
- 2015-12-10: Added consolidated geography label file label_geography_all.csv
- 2016-04-07: Fixed typo in variables_qwipu.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-13: Fixed typo in variables_qwipu.csv (HirAS, HirNS, and status variables)

=== Version 4.0.1 from 4.0

- 2015-02-24: removed obsolete flag values
- 2015-04-01: updated IL, NE geography definitions

=== Version 4.0.2 from 4.0.1

- 2015-04-01: switched NAICS coding from 2007 to 2012

== V4.0.1

== [[changes]] Changes

For a description of how schema files are versioned, see link:../VERSIONING{ext-relative}[main directory].

=== This version (revisions)

- 2015-02-24: Initial release
- 2016-04-07: Fixed typo in variables_qwipu.csv (FrmJbLsS, EarnHirNS and status variables)
- 2016-04-13: Fixed typo in variables_qwipu.csv (HirAS, HirNS, and status variables)

=== Version 4.0.1 from 4.0

- 2015-02-24: removed obsolete flag values
- 2015-04-01: updated IL, NE geography definitions

== V4.0

== v3.5

